# To package and deploy this lambda function, run the following commands:
# npm install
# aws cloudformation package --template ./sam-dev.yml --s3-bucket s37-bot-lambda --s3-prefix slack-bot-lambda --output-template-file output.yml
# aws cloudformation deploy --template-file ./output.yml --stack-name slack-bot-lambda --capabilities CAPABILITY_IAM

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda version of the slack bot
Resources:
  S37BOT:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: Lambda version of the slack bot
      MemorySize: 256
      Timeout: 60
      Policies:
       - AWSLambdaVPCAccessExecutionRole # Managed Policy
      VpcConfig:
        SecurityGroupIds:
          - sg-bb560ac7
        SubnetIds:
          - subnet-fc060cb4
          - subnet-d4917aad
          - subnet-cf0cd295
      Environment:
        Variables:
          NODE_ENV: dev
