# To package and deploy this lambda function, run the following commands:
# npm install
# aws cloudformation package --template ./template2.yml --s3-bucket kiran-s37 --s3-prefix kiran-lambda2 --output-template-file output.yml
# aws cloudformation deploy --template-file ./output.yml --stack-name kiran-stack2 --capabilities CAPABILITY_IAM

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack with Lambda function and API gateway

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
    KiranLambda2:
      Type: 'AWS::Serverless::Function'
      Properties:
        Description: Lambda function to be triggered from another lambda
        FunctionName: BotTriggerFunction
        Handler: index.secondHandler
        Runtime: nodejs8.10
        MemorySize: 256
        Timeout: 60
        Policies:
          - AWSLambdaVPCAccessExecutionRole # Managed Policy
          - Statement:
              Action: ssm:GetParameter
              Effect: Allow
              Resource: arn:aws:ssm:us-west-2:125900505984:parameter/spira/kiran
        VpcConfig:
          SecurityGroupIds:
            - sg-bb560ac7
          SubnetIds:
            - subnet-fc060cb4
            - subnet-d4917aad
            - subnet-cf0cd295
        Environment:
          Variables:
            NODE_ENV: dev
