# To package and deploy this lambda function, run the following commands:
# npm install
# aws cloudformation package --template ./template1.yml --s3-bucket kiran-s37 --s3-prefix kiran-lambda1 --output-template-file output.yml
# aws cloudformation deploy --template-file ./output.yml --stack-name kiran-stack1 --capabilities CAPABILITY_IAM

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack with Lambda function and API gateway

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  KiranAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  KiranLambda1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Main Lambda Function for Slack Bot
      FunctionName: BotEntryFunction
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 256
      Timeout: 60
      Policies:
       - AWSLambdaVPCAccessExecutionRole # Managed Policy
       - Statement:
          Action: ssm:GetParameter
          Effect: Allow
          Resource: arn:aws:ssm:us-west-2:125900505984:parameter/spira/kiran
       - Statement:
          Action: lambda:InvokeFunction
          Effect: Allow
          Resource: arn:aws:lambda:us-west-2:125900505984:function:BotTriggerFunction
      Events:
        allGet:
          Type: Api
          Properties:
            RestApiId: !Ref KiranAPIGateway
            Path: /status
            Method: get
        allPost:
          Type: Api
          Properties:
            RestApiId: !Ref KiranAPIGateway
            Path: /status
            Method: post
      VpcConfig:
        SecurityGroupIds:
          - sg-bb560ac7
        SubnetIds:
          - subnet-fc060cb4
          - subnet-d4917aad
          - subnet-cf0cd295
      Environment:
        Variables:
          NODE_ENV: dev
Outputs:
  KiranGateway:
    Value: !Ref KiranAPIGateway
